name: bong_librarian_check
description: "도서부원 출석 체크 앱"
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  path_provider: ^2.1.4
  provider: ^6.1.2
  url_launcher: ^6.3.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/ibm_plex_mono/IBMPlexMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/ibm_plex_mono/IBMPlexMono-Medium.ttf
          weight: 500        
        - asset: assets/fonts/ibm_plex_mono/IBMPlexMono-Bold.ttf
        - asset: assets/fonts/ibm_plex_mono/IBMPlexMono-Italic.ttf
        - asset: assets/fonts/ibm_plex_mono/IBMPlexMono-BoldItalic.ttf
    - family: IBMPlexSansKR
      fonts:
        - asset: assets/fonts/ibm_plex_sans_kr/IBMPlexSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/ibm_plex_sans_kr/IBMPlexSansKR-Medium.ttf
          weight: 500        
        - asset: assets/fonts/ibm_plex_sans_kr/IBMPlexSansKR-Bold.ttf
          weight: 600
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-Medium.ttf
          weight: 500        
        - asset: assets/fonts/ibm_plex_sans/IBMPlexSans-SemiBold.ttf
          weight: 600
    - family: NotoSansKR
      fonts: 
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-Bold.ttf
          weight: 700
        - asset: assets/fonts/noto_sans_kr/NotoSansKR-ExtraBold.ttf
          weight: 800

  